name: flask-ci

on:
  push:
    branches:
      - main
    paths:
      - "flask/**/*"

jobs:
  build:
    name: build-miniflask
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Update submodule
        run: |
          git submodule update --init --recursive
      - name: Build miniflask
        working-directory: ./flask
        run: |
          docker build -f toynet_mininet/dev.Dockerfile -t miniflask-dev .

  test:
    name: unit-test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        working-directory: ./flask
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
      - name: Update submodule
        run: |
          git submodule update --init --recursive
      - name: Build miniflask
        working-directory: ./flask
        run: |
          docker build -f toynet_mininet/dev.Dockerfile -t miniflask-dev .
      - name: Run tests with pytest
        working-directory: ./flask
        run: |
            source environment/env-dev
            docker network create reclass_network
            flask init-db
            pytest -v --ignore tests/test_sessions.py tests/

  lint:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./flask
        run: |
          pip3 install flake8
          pip3 install pylint
      - name: Lint with flake8
        working-directory: ./flask
        run: |
          flake8 flasksrc --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 flasksrc --count --max-complexity=15 --max-line-length=100 --statistics
