name: react-ci

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'react/**/*'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: ./react
      run: npm install
    - name: Run tests
      working-directory: ./react
      run: npm test

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: "npm install"
        working-directory: ./react
        run: npm i
      - name: "eslint"
        working-directory: ./react
        run: npm run style:check

  check-types:
    name: check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: "npm install"
        working-directory: ./react
        run: npm i
      - name: "check types"
        working-directory: ./react
        run: npm run check-types
    
  check-build:
    name: check build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: "npm install"
        working-directory: ./react
        run: npm i
      - name: "build"
        working-directory: ./react
        run: npm run build
